environment:
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  REDIS_PASS: ${REDIS_PASS}
  HASH_SALT: ${HASH_SALT}
packages:
  - name: p # package
    actions:
      - name: r # redirect
        runtime: 'python:default'
