packages:
  - name: p # package
    actions:
      - name: r # redirect
        runtime: 'python:default'
      - name: hash_to_url
        runtime: 'python:default'
      - name: url_to_hash
        runtime: 'python:default'